### ISSUE TITLE
Top down analysis

### ISSUE THREAD

**Issue by jgphpc** [LLNL/caliper-examples#5]
Hi,

I am trying (for the first time) to run a top down analysis using Quicksilver and [topdown.sh](https://github.com/LLNL/caliper-examples/blob/master/scripts/topdown/topdown.sh)
My json files (reported by Caliper/2.3.0) look a bit different 
```
==> topdown_counters.json.GROUPBY_all <==
[
{"sum#libpfm.counter.BR_MISP_RETIRED.ALL_BRANCHES":"25482765","sum#libpfm.counter.CPU_CLK_UNHALTED.THREAD_P":"15515962999",...

==> topdown_counters.json.GROUPBY_function <==
[
{"sum#libpfm.counter.BR_MISP_RETIRED.ALL_BRANCHES":"17257","sum#libpfm.counter.CPU_CLK_UNHALTED.THREAD_P":"14372485",...
==> topdown_counters.json.GROUPBY_lulesh.phase <==
[
{"sum#libpfm.counter.BR_MISP_RETIRED.ALL_BRANCHES":"25586420",...
```

when compared with [quicksilver_topdown_counters.json](https://github.com/LLNL/caliper-examples/blob/master/datasets/quicksilver_topdown_counters.json.tar.bz2) (Caliper/1.7)

```
{"cali.event.set":"305","event.set#pthread.id":"46913237669632","cali.caliper.version":"1.7.0-dev","mpi.size":"16","lib
pfm.counter.BR_MISP_RETIRED:ALL_BRANCHES":"33","libpfm.counter.CPU_CLK_UNHALTED:THREAD_P":"86425","...
```

My configuration file is [0.conf.txt](https://github.com/LLNL/caliper-examples/files/4462213/0.conf.txt)

My problem is that i can not use the [jupyter](https://github.com/LLNL/caliper-examples/blob/master/jupyter_notebooks/Quicksilver%20Topdown%20Analysis.ipynb) notebook as it will fail with:

```
df = pd.concat(pd.read_json('./topdown_counters.json', orient='records', lines=True, chunksize=1000))


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/apps/dom/UES/jenkins/7.0.UP01/gpu/easybuild/software/PyExtensions/2.7.15.7-CrayGNU-19.10/lib/python2.7/site-packages/pandas-0.23.3-py2.7-linux-x86_64.egg/pandas/core/reshape/concat.py", line 225, in concat
    copy=copy, sort=sort)
  File "/apps/dom/UES/jenkins/7.0.UP01/gpu/easybuild/software/PyExtensions/2.7.15.7-CrayGNU-19.10/lib/python2.7/site-packages/pandas-0.23.3-py2.7-linux-x86_64.egg/pandas/core/reshape/concat.py", line 256, in __init__
    objs = list(objs)
  File "/apps/dom/UES/jenkins/7.0.UP01/gpu/easybuild/software/PyExtensions/2.7.15.7-CrayGNU-19.10/lib/python2.7/site-packages/pandas-0.23.3-py2.7-linux-x86_64.egg/pandas/io/common.py", line 74, in <lambda>
    BaseIterator.next = lambda self: self.__next__()
  File "/apps/dom/UES/jenkins/7.0.UP01/gpu/easybuild/software/PyExtensions/2.7.15.7-CrayGNU-19.10/lib/python2.7/site-packages/pandas-0.23.3-py2.7-linux-x86_64.egg/pandas/io/json/json.py", line 570, in __next__
    obj = self._get_object_parser(lines_json)
  File "/apps/dom/UES/jenkins/7.0.UP01/gpu/easybuild/software/PyExtensions/2.7.15.7-CrayGNU-19.10/lib/python2.7/site-packages/pandas-0.23.3-py2.7-linux-x86_64.egg/pandas/io/json/json.py", line 546, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/apps/dom/UES/jenkins/7.0.UP01/gpu/easybuild/software/PyExtensions/2.7.15.7-CrayGNU-19.10/lib/python2.7/site-packages/pandas-0.23.3-py2.7-linux-x86_64.egg/pandas/io/json/json.py", line 638, in parse
    self._parse_no_numpy()
  File "/apps/dom/UES/jenkins/7.0.UP01/gpu/easybuild/software/PyExtensions/2.7.15.7-CrayGNU-19.10/lib/python2.7/site-packages/pandas-0.23.3-py2.7-linux-x86_64.egg/pandas/io/json/json.py", line 867, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None)
ValueError: Expected object or value
```

Did i miss something obvious ?

Thanks, jg.

**Comment by daboehme** [comment]
Hi @jgphpc ,

Oh my, I need to update these examples. I believe the specific issue here is that the counter names in the json file are now all have the "sum#" prefix, i.e. "sum#libpfm.counter...". So if you modify code in the notebook accordingly it should work.

Meanwhile, Caliper 2.3 actually has some built-in topdown analysis support. It's also woefully undocumented, but this config should do it:

```
CALI_SERVICES_ENABLE=aggregate,event,topdown,report
CALI_REPORT_CONFIG="format json"
CALI_EVENT_ENABLE_SNAPSHOT_INFO=false
```

This should give you a json file with attributes like "topdown.frontend_bound" etc for each region. By default it will only compute the first level of the topdown hierarchy (retiring, bad speculation, frontend and backend bound), add CALI_TOPDOWN_LEVEL=all to get all counters. Also, this requires Caliper built with PAPI support.

I'll update the Quicksilver example to make this easier.
